title: MINERVAS Massive INterior EnviRonments VirtuAl Synthesis
description: Website for MINERVAS
baseurl: "/MINERVAS" # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown
include: ['_pages']

# Google Analytics
google_analytics: UA-111088147-3
